CREATE DATABASE shiny_tracker;
USE shiny_tracker;

CREATE TABLE tblUtenti (
    idUtente INT AUTO_INCREMENT PRIMARY KEY,
    username CHAR(50) UNIQUE NOT NULL,
    email CHAR(100) UNIQUE NOT NULL,
    passwordHash CHAR(255) NOT NULL,
    dataCreazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tblGiochi (
    idGioco INT AUTO_INCREMENT PRIMARY KEY,
    nome Char(100) UNIQUE NOT NULL
);

CREATE TABLE tblMetodi (
    idMetodo INT AUTO_INCREMENT PRIMARY KEY,
    nome CHAR(100) UNIQUE NOT NULL,
    descrizione BLOB(1000)
);

CREATE TABLE tblGiochiMetodi (
    giocoId INT,
    metodoId INT,
    PRIMARY KEY (giocoId, metodoId),
    FOREIGN KEY (giocoId) REFERENCES tblGiochi (idGioco) ON DELETE CASCADE,
    FOREIGN KEY (metodoId) REFERENCES tblMetodi (idMetodo) ON DELETE CASCADE
);

CREATE TABLE tblCacce (
    idCaccia INT AUTO_INCREMENT PRIMARY KEY,
    utenteId INT,
    pokemon CHAR(100) NOT NULL,
     giocoId INT,
     metodoId INT,
    tentativi INT DEFAULT 0,
    isCompleted BOOLEAN DEFAULT FALSE,
    hasShinyCharm BOOLEAN DEFAULT FALSE,
    DataInizio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DataFine TIMESTAMP NULL,
    FOREIGN KEY (utenteId) REFERENCES tblUtenti(idUtente) ON DELETE CASCADE,
    FOREIGN KEY (giocoId) REFERENCES tblGiochi(idGioco) ON DELETE CASCADE,
    FOREIGN KEY (metodoId) REFERENCES tblMetodi(idMetodo) ON DELETE CASCADE
);

CREATE TABLE tblOddsMetodi (
    idOdds INT AUTO_INCREMENT PRIMARY KEY,
    metodoId INT NOT NULL,
    giocoId INT NOT NULL,
    oddsWithoutCharm CHAR(20),
    oddsWithCharm CHAR(20),
    FOREIGN KEY (metodoId) REFERENCES tblMetodi(idMetodo) ON DELETE CASCADE,
    FOREIGN KEY (giocoId) REFERENCES tblGiochi(idGioco) ON DELETE CASCADE
);

INSERT INTO tblGiochi (nome) VALUES
('Pokémon Rosso'),
('Pokémon Blu'),
('Pokémon Verde'),
('Pokémon Giallo'),
('Pokémon Oro'),
('Pokémon Argento'),
('Pokémon Cristallo'),
('Pokémon Rubino'),
('Pokémon Zaffiro'),
('Pokémon Smeraldo'),
('Pokémon Rosso Fuoco'),
('Pokémon Verde Foglia'),
('Pokémon Diamante'),
('Pokémon Perla'),
('Pokémon Platino'),
('Pokémon HeartGold'),
('Pokémon SoulSilver'),
('Pokémon Nero'),
('Pokémon Bianco'),
('Pokémon Nero 2'),
('Pokémon Bianco 2'),
('Pokémon X'),
('Pokémon Y'),
('Pokémon Rubino Omega'),
('Pokémon Zaffiro Alpha'),
('Pokémon Sole'),
('Pokémon Luna'),
('Pokémon Ultraluna'),
('Pokémon Ultrasole'),
('Pokémon Lets Go, Eevee!'),
('Pokémon Lets Go, Pikachu!'),
('Pokémon Spada'),
('Pokémon Scudo'),
('Pokémon Perla Splendente'),
('Pokémon Diamante Lucente'),
('Leggende Pokémon: Arceus'),
('Pokémon Scarlatto'),
('Pokémon Violetto');

INSERT INTO tblMetodi (nome, descrizione) VALUES
('Soft Reset', 'Salva il gioco davanti a un Pokémon statico (come leggendari o starter), poi riavvia ripetutamente il gioco fino a ottenere la versione shiny. Funziona tenendo premuti i pulsanti specifici per il soft reset nella console.'),
('Random Encounter', 'Cammina nell''erba alta o in aree con Pokémon selvatici e avvia battaglie fino a quando non ne incontri uno shiny. È il metodo più semplice ma richiede pazienza.'),
('Breeding', 'Porta due Pokémon compatibili alla Pensione Pokémon o nel Poké Resort e fai deporre uova. Schiudile finché non ottieni uno shiny. Aumenta le probabilità usando il Croma Amuleto.'),
('Masuda', 'Fai accoppiare due Pokémon di **lingue diverse** (es. un Ditto giapponese con un Pokémon italiano) nella Pensione. Le uova avranno una probabilità shiny più alta rispetto all''allevamento normale.'),
('PokéRadar', 'Usa il Poké Radar (ottenibile dopo il Pokédex Nazionale) in aree con erba alta per iniziare catene. Sconfiggi o cattura lo stesso Pokémon senza rompere la catena per aumentare le probabilità di shiny.'),
('Chain Fishing', 'Pescando sempre nello stesso punto senza sbagliare e senza spostarti, aumenti le probabilità di trovare uno shiny. Serve una buona canna e pazienza per non rompere la catena.'),
('Friend Safari', 'Accedi al Safari Amici in Pokémon X/Y (dopo aver finito il gioco), visita i Safari degli amici e cerca Pokémon shiny con un tasso aumentato. Ogni Safari ha 2-3 Pokémon fissi.'),
('DexNav', 'In Rubino Omega/Zaffiro Alpha, seleziona un Pokémon visto dal Pokédex, avvicinati furtivamente e inizia l''incontro. Catene successive aumentano le probabilità e permettono anche mosse/talenti speciali.'),
('SOS Chaining', 'In Sole/Luna e Ultrasole/Ultraluna, indebolisci un Pokémon selvatico e aspetta che chiami aiuto. Fai faint all''alleato e aspetta che ne appaia un altro. Dopo 30+ chiamate le probabilità shiny aumentano notevolmente.'),
('Ultra Wormholes', 'Nel minigioco degli Ultra Varchi (Ultrasole/Ultraluna), viaggia il più lontano possibile per trovare portali rari. I Pokémon all''interno hanno probabilità shiny aumentate, specialmente quelli nei portali colorati.'),
('Overworld Shiny', 'In giochi come Arceus e Scarlatto/Violetto, i Pokémon shiny appaiono già visivamente nel mondo di gioco (spesso con un suono o un effetto brillante). Basta avvicinarsi e catturarli direttamente.'),
('Combo Catch', 'In Lets Go Pikachu/Eevee, cattura consecutivamente lo stesso Pokémon (minimo 11, meglio 31+) per aumentare la probabilità di trovarlo shiny. Usa Aromi e cerca di non rompere la combo.'),
('Max Raid Dens', 'Partecipa ai Raid Dynamax in Spada/Scudo. Alcuni raid, specialmente quelli speciali o ospitati da altri giocatori, hanno probabilità shiny più alte. L''uso del Croma Amuleto influisce anche qui.'),
('Underground Chaining', 'Nella Grandi Sotterranei (Diamante Lucente/Perla Splendente), sconfiggi o cattura lo stesso Pokémon nelle aree nascoste. Dopo una catena di 40, le probabilità shiny aumentano notevolmente.'),
('Mass Outbreaks', 'Quando un''epidemia (outbreak) di Pokémon appare sulla mappa (in Arceus o Scarlatto/Violetto), vai nell''area e cattura o sconfiggi i Pokémon. Le probabilità shiny aumentano dopo 60 incontri.'),
('Picnic Reset', 'In Scarlatto/Violetto, vai in un''area dove spawnano Pokémon desiderati, avvia e chiudi un picnic ripetutamente per forzare il respawn dei Pokémon, sperando che uno sia shiny.'),
('Sandwich Sparkling Power', 'Prepara panini con ingredienti specifici (a fine gioco) per ottenere il potere Sparkling Lvl 3. Aumenta drasticamente la probabilità di incontrare Pokémon shiny in quell''area e tipo.');

INSERT INTO tblGiochiMetodi (giocoId, metodoId) VALUES
-- Prima generazione: non ha Pokémon shiny, rimuovere le associazioni
-- Seconda generazione
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Oro'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Oro'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Oro'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Argento'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Argento'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Argento'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Cristallo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Cristallo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Cristallo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
-- Terza generazione (RSE)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Smeraldo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Smeraldo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Smeraldo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
-- Terza generazione (RFVF)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rosso Fuoco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rosso Fuoco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rosso Fuoco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Verde Foglia'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Verde Foglia'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Verde Foglia'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
-- Quarta generazione (DPP)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
-- Quarta generazione (HGSS)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon HeartGold'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon HeartGold'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon HeartGold'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon HeartGold'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon SoulSilver'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon SoulSilver'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon SoulSilver'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon SoulSilver'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
-- Quinta generazione (BW)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
-- Quinta generazione (B2W2)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco 2'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
-- Sesta generazione (XY)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Chain Fishing')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Friend Safari')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Chain Fishing')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Friend Safari')),
-- Sesta generazione (ORAS)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'DexNav')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Chain Fishing')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'DexNav')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Chain Fishing')),
-- Settima generazione (SM)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining')),
-- Settima generazione (USUM)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Ultra Wormholes')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Ultra Wormholes')),
-- Settima generazione (LGPE)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Lets Go, Pikachu!'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Overworld Shiny')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Lets Go, Pikachu!'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Combo Catch')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Lets Go, Eevee!'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Overworld Shiny')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Lets Go, Eevee!'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Combo Catch')),
-- Ottava generazione (SWSH)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Max Raid Dens')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Max Raid Dens')),
-- Ottava generazione (BDSP)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Underground Chaining')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Underground Chaining')),
-- Ottava generazione (PLA)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Leggende Pokémon: Arceus'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Overworld Shiny')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Leggende Pokémon: Arceus'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Mass Outbreaks')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Leggende Pokémon: Arceus'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset')),
-- Nona generazione (SV)
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Overworld Shiny')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Mass Outbreaks')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Picnic Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Sandwich Sparkling Power')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Overworld Shiny')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Mass Outbreaks')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Picnic Reset')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Sandwich Sparkling Power')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Breeding')),
((SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), (SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'));

INSERT INTO tblOddsMetodi (metodoId, giocoId, oddsWithoutCharm, oddsWithCharm) VALUES
-- Gen 2 (Oro, Argento, Cristallo) - Odds base 1/8192
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Oro'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Argento'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Cristallo'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Oro'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Argento'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Cristallo'), '1/8192', NULL),

-- Gen 3 - Odds base 1/8192
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Smeraldo'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rosso Fuoco'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Verde Foglia'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Smeraldo'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rosso Fuoco'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Soft Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Verde Foglia'), '1/8192', NULL),

-- Gen 4 - Odds base e Masuda Method
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon HeartGold'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon SoulSilver'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), '1/2048', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), '1/2048', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), '1/2048', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon HeartGold'), '1/2048', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon SoulSilver'), '1/2048', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante'), '1/200', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla'), '1/200', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Platino'), '1/200', NULL),

-- Gen 5 - Odds base e Masuda Method
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero 2'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco 2'), '1/8192', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero'), '1/1365', '1/1024'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco'), '1/1365', '1/1024'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Nero 2'), '1/1365', '1/1024'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Bianco 2'), '1/1365', '1/1024'),

-- Gen 6 - X, Y, ORAS - Odds base 1/4096 e metodi vari
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), '1/200', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), '1/200', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Chain Fishing'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon X'), '1/100', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Chain Fishing'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Y'), '1/100', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'DexNav'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Rubino Omega'), '1/100', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'DexNav'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Zaffiro Alpha'), '1/100', NULL),

-- Gen 7 - Sole, Luna, Ultrasole, Ultraluna - Odds base e metodi specifici
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), '1/4096', '1/1365'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Sole'), '1/4096', '1/1024'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Luna'), '1/4096', '1/1024'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultrasole'), '1/4096', '1/1024'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'SOS Chaining'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Ultraluna'), '1/4096', '1/1024'),

-- Let's Go Pikachu, Eevee
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Combo Catch'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Lets Go, Pikachu!'), '1/4096-1/273', '1/2731-1/213'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Combo Catch'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Lets Go, Eevee!'), '1/4096-1/273', '1/2731-1/213'),

-- Gen 8 - Spada, Scudo - Odds base e metodi
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), '1/4096', '1/2731'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), '1/4096', '1/2731'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Spada'), '1/4096-1/455', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Random Encounter'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scudo'), '1/4096-1/455', NULL),

-- BDSP - Diamante Lucente, Perla Splendente
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), '1/99', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'PokéRadar'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), '1/99', NULL),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Diamante Lucente'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Perla Splendente'), '1/683', '1/512'),

-- Leggende Pokémon: Arceus
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Mass Outbreaks'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Leggende Pokémon: Arceus'), '1/4096', '1/158.2'),

-- Gen 9 - Scarlatto, Violetto
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Masuda'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), '1/683', '1/512'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Picnic Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), '1/2048', '1/683'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Picnic Reset'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), '1/2048', '1/683'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Sandwich Sparkling Power'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Scarlatto'), '1/2048', '1/683'),
((SELECT idMetodo FROM tblMetodi WHERE nome = 'Sandwich Sparkling Power'), (SELECT idGioco FROM tblGiochi WHERE nome = 'Pokémon Violetto'), '1/2048', '1/683');
